#!/usr/bin/env bash
set -euo pipefail

SETTINGS_FILE="$HOME/.config/discord/settings.json"

mkdir -p "$(dirname "$SETTINGS_FILE")"

echo "[discord] Installing Discord..."

sudo pacman -S --noconfirm discord

echo "[discord] Checking if the browser is installed..."
if ! command -v discord &>/dev/null; then
  echo "[discord] Discord is not installed, exiting..."
  exit 1
fi

echo "[discord] Patching Discord to disable update checks..."
if [ ! -f "$SETTINGS_FILE" ]; then
  echo "{}" > "$SETTINGS_FILE"
fi

echo "[discord] Patching Discord hyprland keybinds passthrough..."
DESKTOP_FILE="$HOME/.local/share/applications/discord.desktop"

cp /usr/share/applications/discord.desktop "$DESKTOP_FILE"

echo "[discord] Ensuring ELECTRON_OZONE_PLATFORM_HINT=x11 is present in Exec line..."

if ! grep -q "ELECTRON_OZONE_PLATFORM_HINT=" "$DESKTOP_FILE"; then
    sed -i 's|^Exec=|Exec=env ELECTRON_OZONE_PLATFORM_HINT=x11 |' "$DESKTOP_FILE"
    echo "[discord] Patched Exec line with ELECTRON_OZONE_PLATFORM_HINT=x11"
else
    echo "[discord] Exec already contains ELECTRON_OZONE_PLATFORM_HINT — skipping."
fi

jq '. + {"SKIP_HOST_UPDATE": true}' "$SETTINGS_FILE" > "$SETTINGS_FILE.tmp"

mv "$SETTINGS_FILE.tmp" "$SETTINGS_FILE"

echo "[discord] Installing Vencord..."

sh -c "$(curl -sS https://vencord.dev/install.sh)"
