#!/usr/bin/env bash
set -euo pipefail

WITH_GAMES="${OMARCHY_GAMES:-0}"

echo "[additions] Installing system additions..."

if ! pacman -Qi tailscale &>/dev/null; then
  echo "[additions] Tailscale is not installed, installing it..."j

  omarchy-install-tailscale
else
  echo "[additions] Tailscale is already installed, skipping installation"
fi

if ! pacman -Qi bitwarden &>/dev/null; then
  echo "[additions] Bitwarden is not installed, installing it..."
  sudo pacman -S --noconfirm bitwarden
else
  echo "[additions] Bitwarden is already installed, skipping installation"
fi


if [[ "$WITH_GAMES" == 1 ]]; then
  echo "[additions] Installing omarchy games additions..."

  if ! pacman -Qi steam &>/dev/null; then
    echo "[additions] Steam is not installed, installing it..."
    omarchy-install-steam
  else
    echo "[additions] Steam is already installed, skipping installation"
  fi
fi
