#!/usr/bin/env bash
set -euo pipefail

echo "[node] Checking if nvm is installed"
if ! fish -c "type -q nvm" &>/dev/null; then
  echo "[node] nvm is not installed, skipping this script..."
  exit 1
else
  echo "[node] nvm is installed, installing node lts version..."
  fish -c "nvm install lts"
fi

echo "[node] Checking if pnpm is installed"
if ! command -v pnpm &>/dev/null; then
  echo "[node] pnpm is not installed, installing it..."

  curl -fsSL https://get.pnpm.io/install.sh | sh -
else
  echo "[node] pnpm is already installed, skipping installation"
fi

echo "[node] Done."
