#!/usr/bin/env bash
set -euo pipefail

echo "[zen-browser] Installing Zen Browser..."

if ! yay -Qi zen-browser-bin &>/dev/null; then
  echo "[zen-browser] Zen Browser is not installed, installing it..."
  yay -S --noconfirm zen-browser-bin
else
  echo "[zen-browser] Zen Browser is already installed, skipping installation"
fi

echo "[zen-browser] Checking if Sine is already installed..."

SINE_FILE=$(ls ~/.zen/*Default*/chrome/JS/sine.uc.mjs 2>/dev/null || true)

if [[ -n "$SINE_FILE" ]]; then
  echo "[zen-browser] Sine is already installed at:"
  echo "  $SINE_FILE"
  echo "[zen-browser] Skipping Sine installation."
  exit 0
fi

echo "[zen-browser] Sine not found, installing..."

ARCH=$(uname -m)
case "$ARCH" in
        x86_64)         ARCH="x64" ;;
        aarch64)        ARCH="arm64" ;;
        arm64)          ARCH="arm64" ;;
        *)              echo "    ERROR: Unsupported architecture: $ARCH"; exit 1 ;;
esac

echo "-> Detected architecture : $ARCH"

SINE_VERSION=$(curl -s https://api.github.com/repos/CosmoCreeper/Sine/releases/latest | grep tag_name | cut -d '"' -f4)
if [ -z "$SINE_VERSION" ]; then
        echo "    ERROR: Could not fetch latest Sine version"
        exit 1
fi
echo "-> Fetched lastest Sine version: $SINE_VERSION"

echo "-> Downloading Sine binary..."
curl -L -o /tmp/zen-browser-sine "https://github.com/CosmoCreeper/Sine/releases/download/$SINE_VERSION/sine-linux-$ARCH"

chmod +x /tmp/zen-browser-sine

pushd /tmp >/dev/null
sudo ./zen-browser-sine
popd >/dev/null

if [ $? -eq 0 ]; then
  echo "[zen-browser] Done."
  rm /tmp/zen-browser-sine
else
  echo "[zen-browser] Failed to install Sine for Zen Browser."
  exit 1
fi

sudo chown $(whoami):$(whoami) -R ~/.zen/*/chrome/
